layout_spectrum: 1
typography_spectrum: 0.3055455
color:
  saturation: 0.8930208
  brandStrength: 0.835021
  lightness: 0
  rhythmicContrast: 0.5558539
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: "AJ's Japan"
